name: ultra_ui
description: Flutter port of uview-plus with UP-prefixed widgets and 1:1 default styles.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  markdown: ^7.3.1
  qr: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: upicon
      fonts:
        - asset: fonts/upicon.ttf
