import 'example_route.dart';

/// Immutable inventory of every route registered by the uView Plus demo.
class ExampleSourceRoute {
  const ExampleSourceRoute({
    required this.id,
    required this.sourcePath,
    required this.title,
    required this.group,
  });

  final String id;
  final String sourcePath;
  final String title;
  final ExampleRouteGroup group;
}

const List<ExampleSourceRoute> sourceExampleRoutes = <ExampleSourceRoute>[
  ExampleSourceRoute(
    id: 'example/components',
    sourcePath: 'pages/example/components',
    title: 'uview-plus',
    group: ExampleRouteGroup.main,
  ),
  ExampleSourceRoute(
    id: 'example/template',
    sourcePath: 'pages/example/template',
    title: '模板',
    group: ExampleRouteGroup.main,
  ),
  ExampleSourceRoute(
    id: 'example/mine',
    sourcePath: 'pages/example/mine',
    title: '我的',
    group: ExampleRouteGroup.main,
  ),
  ExampleSourceRoute(
    id: 'example/ad',
    sourcePath: 'pages/example/ad',
    title: '广告',
    group: ExampleRouteGroup.main,
  ),
  ExampleSourceRoute(
    id: 'componentsA/transition/transition',
    sourcePath: 'pages/componentsA/transition/transition',
    title: '过渡动画',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/test/test',
    sourcePath: 'pages/componentsA/test/test',
    title: '测试',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/icon/icon',
    sourcePath: 'pages/componentsA/icon/icon',
    title: '图标',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/cell/cell',
    sourcePath: 'pages/componentsA/cell/cell',
    title: '单元格',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/line/line',
    sourcePath: 'pages/componentsA/line/line',
    title: '线条',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/image/image',
    sourcePath: 'pages/componentsA/image/image',
    title: '图片',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/link/link',
    sourcePath: 'pages/componentsA/link/link',
    title: '超链接',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/button/button',
    sourcePath: 'pages/componentsA/button/button',
    title: '按钮',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/loading-icon/loading-icon',
    sourcePath: 'pages/componentsA/loading-icon/loading-icon',
    title: '加载中图标',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/overlay/overlay',
    sourcePath: 'pages/componentsA/overlay/overlay',
    title: '遮罩层',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/loading-page/loading-page',
    sourcePath: 'pages/componentsA/loading-page/loading-page',
    title: '加载页',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/popup/popup',
    sourcePath: 'pages/componentsA/popup/popup',
    title: '弹窗',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/swipeAction/swipeAction',
    sourcePath: 'pages/componentsA/swipeAction/swipeAction',
    title: '滑动单元格',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/sticky/sticky',
    sourcePath: 'pages/componentsA/sticky/sticky',
    title: '吸顶',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/radio/radio',
    sourcePath: 'pages/componentsA/radio/radio',
    title: '单选框',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/checkbox/checkbox',
    sourcePath: 'pages/componentsA/checkbox/checkbox',
    title: '复选框',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/empty/empty',
    sourcePath: 'pages/componentsA/empty/empty',
    title: '内容为空',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/backtop/backtop',
    sourcePath: 'pages/componentsA/backtop/backtop',
    title: '返回顶部',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/divider/divider',
    sourcePath: 'pages/componentsA/divider/divider',
    title: '分割线',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/rate/rate',
    sourcePath: 'pages/componentsA/rate/rate',
    title: '评分',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/gap/gap',
    sourcePath: 'pages/componentsA/gap/gap',
    title: '间隔槽',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/grid/grid',
    sourcePath: 'pages/componentsA/grid/grid',
    title: '宫格',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsA/lazyLoad/lazyLoad',
    sourcePath: 'pages/componentsA/lazyLoad/lazyLoad',
    title: '图片懒加载',
    group: ExampleRouteGroup.componentsA,
  ),
  ExampleSourceRoute(
    id: 'componentsB/dropdown/dropdown',
    sourcePath: 'pages/componentsB/dropdown/dropdown',
    title: '下拉菜单',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/actionSheet/actionSheet',
    sourcePath: 'pages/componentsB/actionSheet/actionSheet',
    title: '上拉菜单',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/parse/parse',
    sourcePath: 'pages/componentsB/parse/parse',
    title: '富文本解析器',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/parse/jump',
    sourcePath: 'pages/componentsB/parse/jump',
    title: '内部链接',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/toast/toast',
    sourcePath: 'pages/componentsB/toast/toast',
    title: '提示消息',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/keyboard/keyboard',
    sourcePath: 'pages/componentsB/keyboard/keyboard',
    title: '键盘',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/slider/slider',
    sourcePath: 'pages/componentsB/slider/slider',
    title: '滑动选择器',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/upload/upload',
    sourcePath: 'pages/componentsB/upload/upload',
    title: '上传',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/notify/notify',
    sourcePath: 'pages/componentsB/notify/notify',
    title: '消息提示',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/countDown/countDown',
    sourcePath: 'pages/componentsB/countDown/countDown',
    title: '倒计时',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/color/color',
    sourcePath: 'pages/componentsB/color/color',
    title: '色彩',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/numberBox/numberBox',
    sourcePath: 'pages/componentsB/numberBox/numberBox',
    title: '步进器',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/countTo/countTo',
    sourcePath: 'pages/componentsB/countTo/countTo',
    title: '数字滚动',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/search/search',
    sourcePath: 'pages/componentsB/search/search',
    title: '搜索',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/badge/badge',
    sourcePath: 'pages/componentsB/badge/badge',
    title: '徽标数',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/tag/tag',
    sourcePath: 'pages/componentsB/tag/tag',
    title: '标签',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/alert/alert',
    sourcePath: 'pages/componentsB/alert/alert',
    title: '警告',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/switch/switch',
    sourcePath: 'pages/componentsB/switch/switch',
    title: '开关',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/collapse/collapse',
    sourcePath: 'pages/componentsB/collapse/collapse',
    title: '折叠面板',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/code/code',
    sourcePath: 'pages/componentsB/code/code',
    title: '验证码',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/noticeBar/noticeBar',
    sourcePath: 'pages/componentsB/noticeBar/noticeBar',
    title: '滚动通知',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/progress/progress',
    sourcePath: 'pages/componentsB/progress/progress',
    title: '进度条',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/tabbar/tabbar',
    sourcePath: 'pages/componentsB/tabbar/tabbar',
    title: 'Tabbar',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/tabbar/tabbar2',
    sourcePath: 'pages/componentsB/tabbar/tabbar2',
    title: 'Tabbar-vue',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/waterfall/waterfall',
    sourcePath: 'pages/componentsB/waterfall/waterfall',
    title: '瀑布流',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/card/card',
    sourcePath: 'pages/componentsB/card/card',
    title: '卡片',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/table/table',
    sourcePath: 'pages/componentsB/table/table',
    title: '表格',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsB/table2/table2',
    sourcePath: 'pages/componentsB/table2/table2',
    title: '表格2',
    group: ExampleRouteGroup.componentsB,
  ),
  ExampleSourceRoute(
    id: 'componentsC/form/form',
    sourcePath: 'pages/componentsC/form/form',
    title: '表单',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/textarea/textarea',
    sourcePath: 'pages/componentsC/textarea/textarea',
    title: '文本域',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/noNetwork/noNetwork',
    sourcePath: 'pages/componentsC/noNetwork/noNetwork',
    title: '无网络提示',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/loadmore/loadmore',
    sourcePath: 'pages/componentsC/loadmore/loadmore',
    title: '加载更多',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/text/text',
    sourcePath: 'pages/componentsC/text/text',
    title: '文本',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/steps/steps',
    sourcePath: 'pages/componentsC/steps/steps',
    title: '步骤条',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/navbar/navbar',
    sourcePath: 'pages/componentsC/navbar/navbar',
    title: '导航栏',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/skeleton/skeleton',
    sourcePath: 'pages/componentsC/skeleton/skeleton',
    title: '骨架屏',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/input/input',
    sourcePath: 'pages/componentsC/input/input',
    title: '输入框',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/album/album',
    sourcePath: 'pages/componentsC/album/album',
    title: '相册',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/avatar/avatar',
    sourcePath: 'pages/componentsC/avatar/avatar',
    title: '头像',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/readMore/readMore',
    sourcePath: 'pages/componentsC/readMore/readMore',
    title: '阅读更多',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/layout/layout',
    sourcePath: 'pages/componentsC/layout/layout',
    title: '布局',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/indexList/indexList',
    sourcePath: 'pages/componentsC/indexList/indexList',
    title: '索引列表',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/indexList/indexList2',
    sourcePath: 'pages/componentsC/indexList/indexList2',
    title: '索引列表(弹窗)',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/tooltip/tooltip',
    sourcePath: 'pages/componentsC/tooltip/tooltip',
    title: '长按提示',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/guide/guide',
    sourcePath: 'pages/componentsC/guide/guide',
    title: '首屏引导',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/popover/popover',
    sourcePath: 'pages/componentsC/popover/popover',
    title: 'Popover弹窗',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/tabs/tabs',
    sourcePath: 'pages/componentsC/tabs/tabs',
    title: '标签',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/list/list',
    sourcePath: 'pages/componentsC/list/list',
    title: '列表',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/swiper/swiper',
    sourcePath: 'pages/componentsC/swiper/swiper',
    title: '轮播',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/scrollList/scrollList',
    sourcePath: 'pages/componentsC/scrollList/scrollList',
    title: '横向滚动列表',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/codeInput/codeInput',
    sourcePath: 'pages/componentsC/codeInput/codeInput',
    title: '验证码输入',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/modal/modal',
    sourcePath: 'pages/componentsC/modal/modal',
    title: '模态框',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/picker/picker',
    sourcePath: 'pages/componentsC/picker/picker',
    title: '选择器',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/calendar/calendar',
    sourcePath: 'pages/componentsC/calendar/calendar',
    title: '日历',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/datetimePicker/datetimePicker',
    sourcePath: 'pages/componentsC/datetimePicker/datetimePicker',
    title: '时间选择',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsC/subsection/subsection',
    sourcePath: 'pages/componentsC/subsection/subsection',
    title: '分段器',
    group: ExampleRouteGroup.componentsC,
  ),
  ExampleSourceRoute(
    id: 'componentsD/qrcode/qrcode',
    sourcePath: 'pages/componentsD/qrcode/qrcode',
    title: '二维码',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/copy/copy',
    sourcePath: 'pages/componentsD/copy/copy',
    title: '复制',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/navbarMini/navbarMini',
    sourcePath: 'pages/componentsD/navbarMini/navbarMini',
    title: '迷你导航',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/box/box',
    sourcePath: 'pages/componentsD/box/box',
    title: '盒子',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/floatButton/floatButton',
    sourcePath: 'pages/componentsD/floatButton/floatButton',
    title: '悬浮按钮',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/cateTab/cateTab',
    sourcePath: 'pages/componentsD/cateTab/cateTab',
    title: '垂直TAB',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/select/select',
    sourcePath: 'pages/componentsD/select/select',
    title: '经典下拉框',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/pagination/pagination',
    sourcePath: 'pages/componentsD/pagination/pagination',
    title: '分页器',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/tree/tree',
    sourcePath: 'pages/componentsD/tree/tree',
    title: '树形',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/dragsort/dragsort',
    sourcePath: 'pages/componentsD/dragsort/dragsort',
    title: '拖动排序',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/cityLocate/cityLocate',
    sourcePath: 'pages/componentsD/cityLocate/cityLocate',
    title: '城市定位',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/title/title',
    sourcePath: 'pages/componentsD/title/title',
    title: '标题',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/pullRefresh/pullRefresh',
    sourcePath: 'pages/componentsD/pullRefresh/pullRefresh',
    title: '下拉刷新',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/virtualList/virtualList',
    sourcePath: 'pages/componentsD/virtualList/virtualList',
    title: '虚拟列表',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/barcode/barcode',
    sourcePath: 'pages/componentsD/barcode/barcode',
    title: '条码',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/cropper/cropper',
    sourcePath: 'pages/componentsD/cropper/cropper',
    title: '图片裁剪',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/signature/signature',
    sourcePath: 'pages/componentsD/signature/signature',
    title: '签名签字',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/agreement/agreement',
    sourcePath: 'pages/componentsD/agreement/agreement',
    title: '弹窗协议',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/markdown/markdown',
    sourcePath: 'pages/componentsD/markdown/markdown',
    title: 'Markdown解析器',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/poster/poster',
    sourcePath: 'pages/componentsD/poster/poster',
    title: '海报生成',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/shortVideo/shortVideo',
    sourcePath: 'pages/componentsD/shortVideo/shortVideo',
    title: '短视频切换',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/pdfReader/pdfReader',
    sourcePath: 'pages/componentsD/pdfReader/pdfReader',
    title: 'PDF阅读器',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/colorPicker/colorPicker',
    sourcePath: 'pages/componentsD/colorPicker/colorPicker',
    title: '颜色选择器',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/coupon/coupon',
    sourcePath: 'pages/componentsD/coupon/coupon',
    title: '优惠券',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/goodsSku/goodsSku',
    sourcePath: 'pages/componentsD/goodsSku/goodsSku',
    title: '商品SKU',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/cascader/cascader',
    sourcePath: 'pages/componentsD/cascader/cascader',
    title: '级联选择器',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'componentsD/choose/choose',
    sourcePath: 'pages/componentsD/choose/choose',
    title: '选项选择器',
    group: ExampleRouteGroup.componentsD,
  ),
  ExampleSourceRoute(
    id: 'template/wxCenter/index',
    sourcePath: 'pages/template/wxCenter/index',
    title: 'wxCenter 仿微信个人中心',
    group: ExampleRouteGroup.template,
  ),
  ExampleSourceRoute(
    id: 'template/keyboardPay/index',
    sourcePath: 'pages/template/keyboardPay/index',
    title: 'keyboardPay 自定义键盘支付',
    group: ExampleRouteGroup.template,
  ),
  ExampleSourceRoute(
    id: 'template/mallMenu/index2',
    sourcePath: 'pages/template/mallMenu/index2',
    title: 'mallMenu-商城分类',
    group: ExampleRouteGroup.template,
  ),
  ExampleSourceRoute(
    id: 'template/mallMenu/index1',
    sourcePath: 'pages/template/mallMenu/index1',
    title: 'mallMenu-商城分类',
    group: ExampleRouteGroup.template,
  ),
  ExampleSourceRoute(
    id: 'template/coupon/index',
    sourcePath: 'pages/template/coupon/index',
    title: 'coupon-优惠券',
    group: ExampleRouteGroup.template,
  ),
  ExampleSourceRoute(
    id: 'template/login/index',
    sourcePath: 'pages/template/login/index',
    title: '美团登录',
    group: ExampleRouteGroup.template,
  ),
  ExampleSourceRoute(
    id: 'template/citySelect/index',
    sourcePath: 'pages/template/citySelect/index',
    title: '城市选择',
    group: ExampleRouteGroup.template,
  ),
  ExampleSourceRoute(
    id: 'template/submitBar/index',
    sourcePath: 'pages/template/submitBar/index',
    title: '提交订单栏',
    group: ExampleRouteGroup.template,
  ),
  ExampleSourceRoute(
    id: 'template/comment/index',
    sourcePath: 'pages/template/comment/index',
    title: '评论',
    group: ExampleRouteGroup.template,
  ),
  ExampleSourceRoute(
    id: 'template/comment/reply',
    sourcePath: 'pages/template/comment/reply',
    title: '评论详情',
    group: ExampleRouteGroup.template,
  ),
  ExampleSourceRoute(
    id: 'template/order/index',
    sourcePath: 'pages/template/order/index',
    title: '订单',
    group: ExampleRouteGroup.template,
  ),
  ExampleSourceRoute(
    id: 'template/login/code',
    sourcePath: 'pages/template/login/code',
    title: '登录获取验证码',
    group: ExampleRouteGroup.template,
  ),
  ExampleSourceRoute(
    id: 'template/address/index',
    sourcePath: 'pages/template/address/index',
    title: '用户地址',
    group: ExampleRouteGroup.template,
  ),
  ExampleSourceRoute(
    id: 'template/address/addSite',
    sourcePath: 'pages/template/address/addSite',
    title: '添加用户地址',
    group: ExampleRouteGroup.template,
  ),
];

ExampleSourceRoute findSourceExampleRoute(String id) {
  return sourceExampleRoutes.firstWhere(
    (route) => route.id == id,
    orElse: () =>
        throw StateError('No source example route registered for $id'),
  );
}
